### ISSUE TITLE
Insert course media after lesson content

### ISSUE THREAD

**Issue by rachelsquirrel** [woocommerce/sensei-media-attachments#12]
When Media attachments are used on the course page, they are inserted between the 'Lessons' heading and the actual lessons. It would be better to insert it after the content or at the end of the page. Or alternatively have an option for placement which the user can control. 

447199-zd-woothemes

**Comment by donnapep** [comment]
This is how course media is displayed on the single course page:
![course-media](https://user-images.githubusercontent.com/1190420/35805710-ecc627f0-0a4a-11e8-8442-081ec2beb9db.jpg)

And this is how it appears on the single course page when there are _Other Lessons_:
![course-media-other-lessons](https://user-images.githubusercontent.com/1190420/35805731-fbcde314-0a4a-11e8-9894-7bf2ae42d150.jpg)

We should change this so that media is displayed after all lessons.
![course-media-after-lessons](https://user-images.githubusercontent.com/1190420/35806017-0d97f07a-0a4c-11e8-9343-bd70a5a3f7dc.jpg)

**Comment by donnapep** [comment]
May need another Sensei hook in order to show after _Other Lessons_.

**Comment by donnapep** [comment]
Can no longer reproduce. May have been fixed by https://github.com/woocommerce/sensei-media-attachments/pull/33.
