### ISSUE TITLE
Cant translate "Lesson Media" term

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/sensei-media-attachments#4]
Link to ticket: https://woothemes.zendesk.com/agent/tickets/340600

User indicates that the string "Lesson Media" cannot be translated. This string is powered by line 166 of **sensei-media-attachments/classes/class-sensei-media-attachments.php**:

```
$html .= '<h2>' . sprintf( __( '%s Media', 'sensei_media_attachments' ), $post_type ) . '</h2>';
```

@danjjohnson mention this isn't ideal as post type variables cannot be localised.

**Comment by WPprodigy** [comment]
Have a ticket about this as well. Nothing seems to be translating with Loco Translate either, I think the textdomain functions aren't working correctly, or the lack of a text domain in the plugin header is causing the issue.

**Comment by danjjohnson** [comment]
Confirmed. Needs a .pot file and a Text Domain in the header.

We should also change that line so that it uses "Course" or "Lesson" rather than the $post_type variable.

**Comment by gfdesign** [comment]
Have you been able to make "Lesson Media" translatable?
Unfortunately, I have the same problem. "Lesson Media" string is not translatable. 
I am using Sensei Media Attachments 1.0.0
Looking forward to your comments
Best regards

**Comment by danjjohnson** [comment]
After investigating this further, the issue is that we use `get_post_type` which always returns the English 'Lesson' or 'Course'. Using `get_post_type_object` to fetch the post type label would solve this.

However, it's still not ideal, because some languages need to change the word order. e.g. in French `Lesson Media` would be `Documents de l’exercice` so `% Media` is no use in that case and we should instead include the complete string.

570378-zd-woothemes
